packages:
  - 'packages/*'
  - 'website'
catalogs:
  dev:
    '@biomejs/biome': 1.9.4
    '@types/node': ^22.15.15
    typescript: ^5.8.3
    globals: ^16.0.0
    vite: ^6.3.5
    vitest: ^3.1.3
    jsdom: ^26.1.0